### ISSUE TITLE
Найти нейронщика

### ISSUE THREAD

**Issue by Kimp13** [Wonder-City-Mayors/Wonder-City#11]
Необходимо найти программиста для создания алгоритма прогнозирования будущих трат.

**Comment by burzeppe** [comment]
Где(Where should i find him)

**Comment by Kimp13** [comment]
> Где(Where should i find him)

I believe you've already tried more than half of possible methods. All the same, why don't you try coming to their sanctuary, the Neuro laboratory? I heard they stayed there all the time.
